// Golden parity: the JS port must reproduce the Python implementation's
// decisions exactly on every fixture — messages byte-for-byte, counts
// number-for-number. Fixtures are generated by tests/gen_golden.py from the
// Python package (the source of truth).
import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { trim } from "../index.js";

const golden = JSON.parse(
  readFileSync(new URL("./fixtures/golden.json", import.meta.url), "utf8")
);

assert.ok(golden.cases.length >= 12, "fixture file looks truncated");

for (const c of golden.cases) {
  test(`parity: ${c.name}`, () => {
    const input = structuredClone(c.messages);
    const r = trim(input, { keep: c.keep, cfg: c.cfg ?? null });
    assert.deepEqual(r.messages, c.expected.messages);
    assert.equal(r.tokensSaved, c.expected.tokensSaved, "tokensSaved");
    assert.equal(r.chunksDropped, c.expected.chunksDropped, "chunksDropped");
    assert.equal(r.changed, c.expected.changed, "changed");
    // inputs are never mutated
    assert.deepEqual(input, c.messages);
  });
}

test("determinism: same input, same output", () => {
  const c = golden.cases[0];
  const a = trim(structuredClone(c.messages), { keep: c.keep });
  const b = trim(structuredClone(c.messages), { keep: c.keep });
  assert.deepEqual(a, b);
});

test("unchanged messages come back as the same object references", () => {
  const c = golden.cases.find((x) => x.name === "noop_gates");
  const input = structuredClone(c.messages);
  const r = trim(input, { keep: c.keep });
  assert.equal(r.changed, false);
  for (let i = 0; i < input.length; i++) assert.equal(r.messages[i], input[i]);
});
